use_default_settings: true

general:
  instance_name: "My SearXNG"
  debug: false

server:
  secret_key: "changeme"
  limiter: false
  image_proxy: true

search:
  formats:
    - html
    - json

ui:
  static_use_hash: true